In [4]:
import pandas as pd

In [5]:
df_heartrate = pd.read_csv("../data/raw/heart_rate_zones.csv")
df_heartrate.head()

   zone  min_percentage  max_percentage        label
0     1              50              60     Recovery
1     2              60              70     Fat Burn
2     3              70              80       Cardio
3     4              80              90  Performance
4     5              90             100      Maximum

In [6]:
df_exercise_metadata = pd.read_csv("../data/raw/exercise_metadata.csv")
df_exercise_metadata

      exercise muscle_group intensity_level
0  Bench Press        Chest          Medium
1        Squat         Legs            High
2     Deadlift         Back            High
3      Running    Full Body          Medium
4      Cycling         Legs          Medium
5         Yoga     Mobility             Low
6         HIIT    Full Body       Very High
7       Rowing         Back          Medium

In [7]:
df_user_metadata = pd.read_csv("../data/raw/users_metadata_messy.csv")
df_user_metadata

,user_id,age,gender,height_m,weight_kg,experience_level,workout_frequency_days_week,fat_percentage
0,U0001,47,Male,1.72,75.8,Advanced,2,21.3
1,U0002,34,Female,1.42,78.7,Advanced,5,20.0
2,U0003,40,Male,1.71,75.2,Advanced,5,27.8
3,U0004,23,Female,1.98,83.1,Beginner,4,15.6
4,U0005,39,Male,1.49,78.1,Advanced,2,21.5
...,...,...,...,...,...,...,...,...
1231,U0894,50,Male,1.83,72.8,Beginner,5,18.0
1232,U0693,44,Male,1.66,NaN,Beginner,3,NaN
1233,U0728,19,Male,1.84,84.0,Beginner,5,14.2
1234,U0363,31,F,1.89,49.1,Beginner,5,24.5
1235,U0597,41,Female,1.82,96.6,Beginner,5,7.5

In [8]:
df_workout_session = pd.read_csv("../data/raw/workout_sessions_messy.csv")
df_workout_session

,user_id,date,exercise,sets,reps,weight_kg,session_duration_hr,calories_burned,avg_bpm,max_bpm,water_intake_l,workout_type
0,U1186,2024-01-25,cycling,NaN,NaN,NaN,NaN,198.0,156.0,176,1.07,Cardio
1,U0316,2024-01-16,Bench Press,3.0,5.0,NaN,0.56,235.0,90.0,112,0.73,STRENGTH
2,U0614,2024-08-03,Cycling,NaN,NaN,NaN,1.28,438.0,149.0,163,NaN,Cardio
3,U0355,2024-10-26,Squat,4.0,5.0,NaN,0.51,237.0,100.0,120,0.49,Strength
4,U0780,2024-07-02,Rowing,NaN,NaN,NaN,0.83,235.0,153.0,177,0.52,Cardio
...,...,...,...,...,...,...,...,...,...,...,...,...
153745,U0896,2024-08-17,Running,NaN,NaN,NaN,0.62,425.0,129.0,147,0.32,Cardio
153746,U1043,2024-02-05,Squat,3.0,5.0,83.3,1.06,415.0,133.0,153,0.58,Strength
153747,U0499,2024-10-06,Cycling,NaN,NaN,NaN,1.18,300.0,152.0,166,0.65,Cardio
153748,U0103,2024-11-14,Rowing,NaN,NaN,NaN,1.49,544.0,111.0,134,0.66,Cardio
153749,U0375,2024-05-15,Running,NaN,NaN,NaN,1.16,570.0,134.0,152,NaN,Cardio